image: mcr.microsoft.com/dotnet/core/sdk
stages:
  - build
  - test
  - publish
build:
  stage: build
  script:
    - 'dotnet restore'
    - 'dotnet build'
test:
  stage: test
  script:
    - 'dotnet test test1/test.csproj'
publish:
  stage: publish
  script:
    - 'dotnet publish CustomerAPI/CustomerAPI.csproj'
  